# Multi-Source OOD Computation — Density-Based Typical Set Reference

This notebook computes/caches summary diagnostics using the density-based typical-set detector from `density_based.ipynb`. For each assumed model and summary dimension, training simulations are passed through the summary network, a normalizing-flow density estimator `q_phi(z)` is trained on the latent summaries, and a separate calibration simulation estimates the central 90% typical interval. A third held-out simulator sample, not used for training or reference-distance calibration, validates the learned density by comparing simulator summaries against flow-generated summaries using MMD and C2ST.

In [1]:
from pathlib import Path
import sys

import pandas as pd

PROJECT_DIR = Path("/Users/yimingzang/Documents/Project/benchmark2")
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from benchmark.examples.diffusion.config import TrainingConfig
from benchmark.examples.diffusion.results.multisource_pipeline import (
    all_observed_paths,
    compute_or_load_all_observed,
    reference_path,
)
from benchmark.examples.diffusion.results.observed_datasets import OBSERVED_DATASETS
from benchmark.examples.diffusion.results.summary_diagnostic import MODELS, load_references

INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/opt/anaconda3/envs/benchmark2/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
INFO:bayesflow:Using backend 'jax'

In [2]:
from tqdm.auto import tqdm as original_tqdm
import bayesflow.approximators.helpers.samplers as bf_samplers
import bayesflow.approximators.helpers.conditions as bf_conditions


def quiet_tqdm(*args, **kwargs):
    kwargs["disable"] = True
    return original_tqdm(*args, **kwargs)


bf_samplers.tqdm = quiet_tqdm
bf_conditions.tqdm = quiet_tqdm

## Configuration

In [3]:
summary_configs = {
    "S=D": TrainingConfig(summary_multiplier=1),
    "S=2D": TrainingConfig(summary_multiplier=2),
    "S=4D": TrainingConfig(summary_multiplier=4),
    "S=6D": TrainingConfig(summary_multiplier=6),
}

metric = "typical"
num_samples = 2048
mmd_samples = 512
batch_size = 8
recompute = False
recompute_references = True

OBSERVED_DATASETS
# First run: keep recompute_references=True to train/cache *_typical density references.
# Later runs can set recompute_references=False to reuse them.
# Typical references train one density flow per summary dimension × assumed model.

('empirical',
 'simulated_from_m0',
 'simulated_from_m1',
 'simulated_from_m2',
 'simulated_from_m3',
 'm3_fast_30',
 'm3_slow_30',
 'm3_fast_slow_30')

## Compute Or Load Cached Results

In [4]:
diagnostics_by_summary = {}

for label, config in summary_configs.items():
    print(f"Computing/loading {label} ({config.summary_label})")
    diagnostics_by_summary[label] = compute_or_load_all_observed(
        config=config,
        metric=metric,
        num_samples=num_samples,
        mmd_samples=mmd_samples,
        batch_size=batch_size,
        recompute=recompute,
        recompute_references=recompute_references,
    )

Computing/loading S=D (S1D)

INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 168ms/step - loss: 5.4709
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3128
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3046
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2777
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2591
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2425
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2467
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2528
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.2115
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2305
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2094
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2041
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2136
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2081
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2188
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.2048
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1976
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1747
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.1725
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1863
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1509
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1564
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1467
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.1544
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1492
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1419
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.1458
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.1336
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1274
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1245
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5.1380
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.1394
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1337
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1344
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1430
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1207
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1327
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1366
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1164
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1267
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1097
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1227
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5.1076
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 5.1051
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.1151
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1259
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1104
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1082
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.1115
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1050
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1104
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0918
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0824
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0834
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1038
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0821
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0918
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1234
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0839
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0790
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0753
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0877
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0858
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0733
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0720
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0731
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0603
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0569
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0752
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0705
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0735
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0759
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0661
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0616
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0526
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0549
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0632
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0681
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0577
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0365
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0544
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0426
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0500
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0642
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0438
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0700
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0439
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0449
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0375
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0348
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0295
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0367
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0409
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0309
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0277
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0216
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0425
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0421
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0287
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0355
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0255
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0207
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0204
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0263
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0241
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0357
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0218
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0136
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0320
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0206
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0170
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0300
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0012
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0093
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0125
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0079
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0093
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0071
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0046
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.0034
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9863
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.9899
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.9809
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9793
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9823
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.9948
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9816
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9875
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9950
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9791
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.9742
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 4.9802
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4.9781
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9730
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9823
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9825
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9670
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9859
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9797
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9894
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.9745
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9682
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9624
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9697
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9758
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9504
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.9588
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.9607
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9506
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9557
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9679
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9451
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9600
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9525
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9602
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9508
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9429
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9476
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9585
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9488
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9468
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9522
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9423
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9461
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.9444
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9424
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9338
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9440
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9369
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9435
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9401
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9415
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9454
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9349
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9298
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9405
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9327
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9341
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9304
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9392
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9285
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9249
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9242
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9132
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9254
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9145
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9283
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9139
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9251
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9139
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9138
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9195
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9210
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9162
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9110
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9094
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9105
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9130
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9189
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9155
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9104
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9115
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9104
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9152
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4.9091
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.8998
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9009
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9117
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9051
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9071
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9037
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9042
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8925
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9086
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9001
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9030
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8957
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8978
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9045
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9015
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9101
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9002
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9028
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8967
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9016
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8957
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8994
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8954
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9026
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9008
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9048
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.8967
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8842
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9043
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8976
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.8928
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9001
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.8949
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9077
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8970
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8944
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8996
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8884
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8931
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.8907
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9002
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9047
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8968
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9001
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8978
Restoring model weights from the end of the best epoch: 233.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 147ms/step - loss: 6.6654
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4476
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3472
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3201
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3269
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.2729
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2449
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2221
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2160
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2168
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1833
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1837
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.2063
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1773
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1965
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1764
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1394
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1233
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1232
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1477
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1085
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1108
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1139
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0957
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0754
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0986
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0931
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0799
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0975
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0533
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0686
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0728
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0410
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0852
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0627
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0534
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0576
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0417
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0216
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0234
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0143
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0345
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0277
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0291
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0248
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0383
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0344
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0071
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9947
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0036
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9936
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0058
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9823
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9815
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9956
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0061
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9982
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9829
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9824
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9940
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9982
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9800
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9772
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9709
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9620
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9558
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9740
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9730
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9464
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9429
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9742
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9577
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9387
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9495
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9405
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9339
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9157
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9300
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9391
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9479
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9370
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9313
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9126
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9146
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9143
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9042
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9091
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9071
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9156
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9073
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9076
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8905
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8900
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8793
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8863
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8670
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8717
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8631
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8684
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8649
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8751
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8590
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8695
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8672
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8650
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8502
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8662
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8629
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8637
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8557
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8382
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8482
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8423
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8594
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8516
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8432
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8236
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8319
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8271
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8127
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8279
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8213
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8279
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8138
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8231
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8092
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8300
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8380
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8158
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8079
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8046
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8070
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8095
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8061
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8029
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7961
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7927
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7978
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.7819
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7635
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7909
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7658
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7827
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7893
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7591
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7748
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7715
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7610
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7721
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7528
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7474
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7733
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7559
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7481
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7648
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7476
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7528
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7431
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7520
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7434
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7388
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7377
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7282
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7403
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7390
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7280
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7201
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7313
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7344
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7223
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7147
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7175
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7120
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7142
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7292
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7119
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7080
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7027
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7155
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7260
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.6975
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6960
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7063
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7040
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6919
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6960
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7099
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.6965
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7047
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6949
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7014
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6960
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6915
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6967
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6915
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6904
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6818
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6826
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6903
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6809
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6726
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6829
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6744
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6601
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6685
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6723
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6621
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6781
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6666
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6686
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6586
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6715
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6735
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6690
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6619
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6517
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6614
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6580
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6675
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6634
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6575
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6550
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6571
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6579
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6518
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6642
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6628
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6579
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6686
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6397
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6672
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6537
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6532
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6494
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6683
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6468
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6559
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6508
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6486
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6483
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6425
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6575
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6453
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6507
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6538
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6556
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6506
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.6530
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6509
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6637
Epoch 250: early stopping
Restoring model weights from the end of the best epoch: 230.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 147ms/step - loss: 6.8114
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6749
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5965
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5907
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5391
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5339
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5291
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5173
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.5012
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4903
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5014
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4925
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4866
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4819
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4570
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4500
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.4364
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4590
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4386
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4231
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4113
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3992
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4082
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4343
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4039
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4007
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3762
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.4143
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3964
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4032
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3946
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3591
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3829
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3943
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3873
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3589
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3679
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3640
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3378
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3332
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3409
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3301
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.3300
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3263
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3496
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3470
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3311
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3346
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3052
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3222
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.3237
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3173
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3286
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2947
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3187
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2928
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2928
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2699
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.2954
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2939
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3066
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2661
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2648
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2794
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2597
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2769
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2777
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2816
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2599
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2462
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2574
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2719
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2503
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.2546
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2641
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2474
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2355
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2718
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2426
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2275
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2152
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2352
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2344
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2149
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2315
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2414
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2451
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2210
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2126
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2192
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2034
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2167
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2103
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1818
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1842
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1979
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1710
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1809
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1898
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2074
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1777
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2036
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1740
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1638
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1678
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1601
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1570
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1512
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1656
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1656
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1582
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1728
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1552
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1611
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1355
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1571
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1542
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1368
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.1384
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1270
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1398
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1304
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1310
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1180
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1201
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1377
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1299
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1042
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1006
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1133
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1146
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0924
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1066
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1176
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1052
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1035
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0991
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1094
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0973
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0937
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0819
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0875
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0984
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0977
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0674
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0855
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0580
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0695
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0685
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0701
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0582
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0716
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0687
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0623
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0629
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0487
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0647
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0481
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0669
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0609
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0515
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0453
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0527
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0284
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0364
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0363
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0408
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0328
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0250
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0234
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0490
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0334
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0257
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0224
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0274
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0184
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0245
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0024
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0016
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0131
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0243
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0189
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0226
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0170
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0044
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0078
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0000
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0081
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9983
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0104
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0081
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9878
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9993
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9961
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9968
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9967
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0114
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9899
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9864
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9940
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9881
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9870
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9767
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9855
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9724
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9801
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9769
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9891
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9864
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9761
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9718
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9772
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9775
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9760
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9671
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9636
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9689
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9642
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9672
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9617
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9768
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9697
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9639
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9705
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9822
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9633
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9769
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9688
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9522
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9677
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9608
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9580
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9645
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9518
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9635
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9610
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9700
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9565
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9491
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9597
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9671
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9611
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9608
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9570
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9612
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9535
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9644
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9626
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9604
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9528
Restoring model weights from the end of the best epoch: 239.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 139ms/step - loss: 9.2114
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.8508
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.7332
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6684
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6275
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6033
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.5575
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4983
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.5204
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.4717
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4716
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4395
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4406
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4255
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4321
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3936
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.3733
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3283
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3066
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3147
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2821
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2675
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2894
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2770
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2572
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2646
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2742
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.2544
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2447
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2190
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2220
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2011
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2067
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1961
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1811
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1722
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1375
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1498
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1345
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1323
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1303
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1371
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.1301
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1526
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1116
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1080
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0722
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0547
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0573
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0678
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.0588
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0638
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0376
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0447
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0547
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0454
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0108
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.0049
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0087
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9882
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9799
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9699
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9943
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9760
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9910
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.9861
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9594
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9329
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9477
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9405
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9046
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9292
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.8961
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9103
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9107
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9220
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8865
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8666
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8496
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8593
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8722
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8999
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8478
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8194
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8183
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8374
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8686
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.8028
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8067
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8022
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7766
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7639
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7750
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7372
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.7542
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7710
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7613
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7596
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7182
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7298
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6991
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.6954
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6863
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6972
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7220
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7107
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6952
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6707
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.7018
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6731
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6528
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6309
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6619
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6172
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6277
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6031
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6207
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6143
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6313
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6203
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5978
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5740
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6228
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5921
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5570
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5668
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6003
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.5859
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5560
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5329
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5222
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5096
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5136
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5176
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5386
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5432
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5121
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4992
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5020
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4846
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4737
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.4790
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4577
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4542
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4736
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4224
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4636
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4840
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.4559
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4877
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4152
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4528
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4313
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4154
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3952
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.4374
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3837
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3647
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3865
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3807
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3825
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3383
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.3478
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3733
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3835
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3781
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3132
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3454
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3272
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.3091
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3310
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3210
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3228
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3001
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3336
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3285
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2963
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3029
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2752
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3115
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2967
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2598
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2597
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2855
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2856
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2396
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2776
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2513
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2473
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2684
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2666
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2417
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2601
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2556
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2322
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2423
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2326
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.2195
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2443
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2207
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2471
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2250
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2175
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2240
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.2172
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1934
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1940
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2016
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1900
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2089
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1885
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1839
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1800
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1942
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1724
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1859
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1595
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1795
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1933
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1850
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1660
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1597
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1714
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1579
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1519
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1446
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1759
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1637
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1602
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1489
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1909
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1517
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1701
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1519
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1597
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1437
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1562
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1403
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.1764
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1740
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1739
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1712
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1697
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1391
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1376
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1752
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1307
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1623
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1681
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1781
Restoring model weights from the end of the best epoch: 247.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.

Computing/loading S=2D (S2D)

INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 157ms/step - loss: 6.7935
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4245
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.6680
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3355
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2213
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0719
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9415
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8522
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.7692
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8110
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.7671
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6046
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4746
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3575
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4499
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3165
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2879
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.4319
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3567
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2101
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1645
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1538
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0440
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2349
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0595
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0143
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9170
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0053
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2265
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0494
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9430
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0341
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8181
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9681
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9572
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.8614
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8682
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8757
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9092
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7445
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8482
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9601
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7322
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.6704
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5995
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6702
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6737
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7182
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7238
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7766
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.6370
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6907
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6564
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6345
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6210
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6292
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6007
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4438
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.5129
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6182
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5769
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6572
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4413
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5571
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6453
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.6389
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5155
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5762
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5879
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4252
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3953
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4394
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3574
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.3262
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4055
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3981
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3166
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4946
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4544
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5252
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.4387
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3309
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3357
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2656
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3795
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3081
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2806
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.2299
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1.3684
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.3243
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2259
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2005
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2287
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2764
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1546
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2088
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2249
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.2259
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1992
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1257
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0556
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1683
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2491
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1431
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1304
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0812
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1055
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1931
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1671
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0715
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0067
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9917
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0451
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0940
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0652
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0902
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9660
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0144
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0161
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0124
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0027
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9614
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0132
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9871
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9527
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9974
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9619
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9674
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9414
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9155
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9139
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8479
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8886
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0401
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0106
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9282
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9238
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9130
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0234
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9142
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8909
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8195
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8443
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7961
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8858
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8111
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8106
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7794
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8859
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8547
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8342
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7376
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7593
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7194
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8200
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7615
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7543
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7215
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7178
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7440
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7089
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6616
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7195
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7401
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6867
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6642
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6745
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6150
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6395
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6553
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6445
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6836
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6721
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6663
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6653
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6462
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6051
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6186
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6592
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6462
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6120
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6247
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6023
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5934
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5828
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6163
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5943
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5930
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6407
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5906
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5996
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5373
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5830
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5852
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5259
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5701
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5211
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5279
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5474
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5110
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5416
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5184
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5189
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5008
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5132
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4874
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5006
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5211
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5329
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4766
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4980
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4541
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4687
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4749
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4723
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5022
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4689
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4444
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4645
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4841
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4672
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4337
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4296
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4562
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4445
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4374
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4555
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4669
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4182
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4744
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4312
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4457
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4362
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4731
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4603
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4619
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4235
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4311
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4336
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4291
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4312
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3728
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4384
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4051
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3841
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4035
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4135
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4799
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4211
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4199
Restoring model weights from the end of the best epoch: 242.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 151ms/step - loss: 8.3240
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.7740
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.7856
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3797
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0049
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8076
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4776
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.6192
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3718
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3100
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3120
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1379
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9041
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8665
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8374
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7548
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5338
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5825
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5934
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5773
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5970
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4765
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.3014
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2461
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1611
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1083
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2123
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2121
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1725
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2168
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.3548
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1719
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1941
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9973
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9169
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9566
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8478
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7855
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9270
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8231
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8639
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7612
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7821
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6505
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6964
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6533
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5148
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7152
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6092
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7588
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7474
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4714
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5340
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3834
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5492
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4546
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4693
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5592
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4935
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4783
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4101
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3748
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4145
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3180
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.3109
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3023
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3299
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3287
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3199
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2621
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2531
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2021
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1104
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0679
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1851
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1688
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0677
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2529
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1003
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0607
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2853
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1568
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0192
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2495
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1501
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0163
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.0540
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0258
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0183
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0063
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1000
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1195
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1060
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1298
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0248
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0986
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1051
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1899
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0393
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.1353
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1865
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.1709
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1990
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1623
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2565
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1469
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2223
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1725
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.3222
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1386
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2326
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2968
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2878
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3196
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3498
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.3171
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3605
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3620
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2892
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4354
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4853
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4450
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.4747
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3860
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4294
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4117
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4162
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4436
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5098
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.4872
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4566
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4536
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4706
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4737
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5332
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5542
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.5578
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5422
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6021
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6109
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6548
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6280
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6621
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.6750
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6775
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6087
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6978
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7123
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7113
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6766
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.7205
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7271
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7704
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7491
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7677
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6921
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.7350
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.8322
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7376
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7499
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7827
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7606
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8109
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8032
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8337
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8339
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8184
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9385
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9329
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8903
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.8800
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9028
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7932
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8577
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9315
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8704
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9157
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.9861
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9345
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9770
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9843
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9356
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9376
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9871
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.9435
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0160
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0172
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0857
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0476
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0184
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.0747
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1071
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9990
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0768
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0616
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0983
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.0531
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0934
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0864
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1487
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1788
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1684
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1360
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.1437
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1598
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1442
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1363
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1162
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1323
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2030
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.1867
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1688
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1704
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1507
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1694
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2194
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1828
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2223
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2157
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2002
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2338
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2613
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2454
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2360
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.2191
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2499
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2016
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2216
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2524
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2354
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2282
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2204
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2169
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2043
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2327
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2653
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2712
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2620
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2443
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2466
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2556
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2249
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2871
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2421
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2843
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2254
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2611
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2939
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2812
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2863
Restoring model weights from the end of the best epoch: 248.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 137ms/step - loss: 8.4847
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8599
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.5852
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1235
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9539
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6145
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4854
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2412
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0266
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0189
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9566
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8635
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7934
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5872
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6074
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3346
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3394
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3241
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3014
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2042
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0144
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0396
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1440
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1906
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1097
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1344
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0087
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9302
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7254
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7893
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8049
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7795
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8301
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5984
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7334
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5440
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7479
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3839
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4234
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4743
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4116
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4807
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3774
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3084
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4309
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4096
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1832
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2542
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1239
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0902
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2191
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3061
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2592
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3526
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2551
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1274
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1751
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3611
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1400
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0663
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1800
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0062
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1122
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0786
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1207
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0666
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.0767
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0420
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1099
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0919
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1209
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.2430
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3337
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.2201
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3908
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2152
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3252
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3535
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3343
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2437
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4472
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.4329
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4150
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3893
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4426
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4551
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3668
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3896
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.4613
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4000
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5041
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5859
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4275
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3852
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.3479
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.5781
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6284
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6329
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4992
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.5622
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8372
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7291
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7776
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.6902
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7721
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6928
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7016
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6884
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7321
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7085
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.7330
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6866
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8727
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -0.8403
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8473
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9092
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9115
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.8973
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9474
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0009
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9359
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9983
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9184
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0300
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.9077
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7456
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9989
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0996
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1084
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.0315
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9929
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9712
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9719
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.0940
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1779
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1495
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.1485
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1357
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.1406
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1852
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2063
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1849
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.1801
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2583
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2397
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2362
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2526
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2004
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2706
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3273
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2728
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3022
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3319
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4135
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2640
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.3196
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2339
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.2669
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3380
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.3818
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4534
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4720
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4677
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4139
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.3890
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4562
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4755
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5123
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4802
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4042
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5210
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5904
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5524
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5614
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5269
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5263
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5822
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5704
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.6354
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5824
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5640
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5830
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5962
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6207
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.6072
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6355
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6511
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.6000
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6747
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6656
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6896
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.7094
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6663
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6376
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6499
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6274
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7450
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.7155
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7000
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7059
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7219
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7764
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6821
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7530
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.7662
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7582
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8033
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8220
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7927
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8063
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8767
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.8249
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8021
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7240
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.7756
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8305
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7830
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8394
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.8822
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8321
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8423
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8208
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8509
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9056
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8243
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.8171
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8360
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8683
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8738
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8738
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8840
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.9268
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8510
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9188
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8910
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8868
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8925
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8386
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.8706
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9110
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9101
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8881
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9113
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8838
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8838
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.9091
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8687
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8986
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9005
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -1.8319
Restoring model weights from the end of the best epoch: 232.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 140ms/step - loss: 12.8466
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8612
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.3868
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8302
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.3163
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9558
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.6776
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3934
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4109
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.2649
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.9396
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6443
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6150
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5756
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2732
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.4688
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6917
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1740
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9962
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9696
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9576
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1320
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.9395
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6971
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4595
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5204
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8170
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8430
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3885
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.7459
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.7561
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4122
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2156
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1323
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3387
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2936
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1866
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.1506
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9840
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8524
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8579
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7762
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7589
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8990
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8562
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.7888
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7960
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6554
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5874
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6996
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5821
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5405
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.5952
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4963
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5002
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3865
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4211
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4114
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2533
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2781
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0666
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0756
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1549
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0737
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0797
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0568
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9083
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9357
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0004
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0132
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9840
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7304
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8893
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9146
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9051
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.7712
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5253
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6380
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5940
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6545
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9178
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5367
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.5592
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6343
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4261
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5242
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4133
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5684
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4568
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2466
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.2704
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2721
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3784
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2887
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2083
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2065
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1693
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2417
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0258
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2755
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3172
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1780
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0795
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.0315
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0375
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1615
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0738
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0761
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.0951
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2289
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.1586
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1869
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2213
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2074
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1210
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1461
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.1741
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.1347
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.2905
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3874
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3221
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.3486
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4306
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5038
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.4889
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5257
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4053
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4547
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5042
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.4854
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5942
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.5433
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5849
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6566
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6566
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.5797
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7370
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.6720
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.7234
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8057
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8699
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8624
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7254
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7846
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8632
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.7681
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7437
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.7236
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.8343
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9647
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9692
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9348
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.0224
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0517
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0655
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0681
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0915
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -0.9268
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0347
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.2124
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.0935
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1358
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1408
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1842
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1661
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2322
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1524
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.1783
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3041
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3148
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2296
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3628
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.2553
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.3521
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3443
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4086
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3474
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.3509
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4723
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.5367
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4990
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5461
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4720
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4848
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5465
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.4788
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.4581
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5407
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5826
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5462
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5769
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5711
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.6612
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6207
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6312
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.5797
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6404
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6577
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7220
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.6723
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6597
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7166
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.6908
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7000
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7899
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7407
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.7277
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7618
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8037
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7660
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7944
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8381
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7684
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.8270
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8143
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8466
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8184
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7763
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8695
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8429
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.8289
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.7949
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8482
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8998
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9003
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8301
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8742
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.9212
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8932
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9344
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9422
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8805
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8597
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.9306
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8600
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8776
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8475
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9472
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9430
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8326
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.8625
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9782
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9273
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9444
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9338
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9626
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9432
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -1.9051
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.9704
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -1.8961
Restoring model weights from the end of the best epoch: 242.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.

Computing/loading S=4D (S4D)

INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 152ms/step - loss: 7.6464
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -2.5351
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -5.0316
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -6.3996
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.2297
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -7.6960
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.2480
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.4868
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.5985
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.8056
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.5962
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.9007
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.0789
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -9.2569
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.4144
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.5754
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.7884
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.0987
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.9767
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.0191
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.7683
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -10.1885
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.2737
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.5825
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7352
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.4662
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.6257
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7513
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.4588
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.2664
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.6097
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7608
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -10.7448
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9630
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9624
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.2340
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9467
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.0741
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9403
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.0949
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -11.5210
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.2498
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.2866
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5885
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.3890
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.3596
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6670
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7049
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -11.7252
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5061
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6664
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5517
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7940
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9916
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7257
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9009
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7903
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7754
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.0123
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6849
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9863
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.8117
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9850
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.2043
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9918
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7604
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.0223
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.0139
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9121
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2366
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2914
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.4862
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9243
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3507
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2868
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4869
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4655
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3235
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.6091
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6083
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4249
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6772
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8044
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6544
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8776
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.9795
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6716
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3225
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8520
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8084
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7921
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7879
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -12.8878
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7352
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7687
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.9824
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.0964
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1929
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.0444
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.9925
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1265
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.0408
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1793
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3013
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2705
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1807
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1700
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.9419
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4026
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4116
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2309
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2763
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.3022
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5585
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3749
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3505
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4434
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.7183
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4342
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.1580
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4019
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.6926
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4582
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5975
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6979
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6908
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.5805
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8757
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8624
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6834
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6447
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8223
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6924
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.7691
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6906
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8898
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9408
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8176
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9779
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9882
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.0606
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9722
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9943
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.0585
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.0619
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1319
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.0408
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -14.1728
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3040
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1352
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1155
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2267
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2109
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3129
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.3670
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3024
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3670
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5388
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5751
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5362
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4587
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.4208
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5618
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4474
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4847
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5607
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5221
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4987
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.6023
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6625
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5491
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6814
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5389
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7806
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7455
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.8176
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7942
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7429
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7108
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7621
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9554
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7662
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.8193
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8838
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8784
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9748
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8712
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9343
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9252
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.9814
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9307
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9512
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9163
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9742
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0358
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0064
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.0968
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0316
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1051
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1389
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0825
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0672
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -15.1662
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1074
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2109
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2458
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1531
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1920
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1798
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2674
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.2307
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2120
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1991
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2311
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3820
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3041
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3407
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.3380
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3394
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3001
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2973
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3766
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2980
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3514
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3630
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3376
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3396
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4171
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3211
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4040
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4067
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3857
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4086
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3550
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3709
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3873
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4752
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.4734
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4033
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4840
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3790
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4480
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4444
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3898
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -15.4114
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4343
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4340
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4429
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4376
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3660
Restoring model weights from the end of the best epoch: 240.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 157ms/step - loss: 13.3610
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6661
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -2.9268
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -4.6711
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -5.7000
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -6.1449
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -6.7100
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -7.0736
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.0257
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.5671
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.9877
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.1391
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.1444
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.5659
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.9821
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -9.0181
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.0150
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.2676
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.9356
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.4665
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.5690
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.8608
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -9.9745
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.7486
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.1514
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.3683
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.2965
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.2515
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.5133
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.6139
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -10.3283
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.8387
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.6712
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.8184
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.8309
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9423
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7860
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.8500
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.0516
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.4207
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.2825
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -11.0782
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.0888
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.2618
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.4343
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5624
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6689
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7469
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -11.8582
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6151
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5949
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6313
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9035
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9117
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.8380
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2368
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.2536
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2855
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2722
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.5738
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7041
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7268
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.5377
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.4322
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4475
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4675
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7323
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6838
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6725
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6884
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7010
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -12.7566
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.0563
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.9733
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1905
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1749
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8714
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1417
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.1510
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.9098
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2657
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3342
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3231
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2813
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3338
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.4356
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4768
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4728
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3798
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5393
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5871
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4567
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.8419
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.7975
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9497
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8001
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8400
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9303
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8129
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8149
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1014
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1746
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9934
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8952
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1445
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1980
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -14.2763
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2007
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2511
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3799
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4787
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5887
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4316
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4102
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4900
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6492
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6150
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4683
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6631
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6365
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8529
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7342
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8460
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6882
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.7137
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9129
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0270
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0969
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1391
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -14.9333
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9796
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0845
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1160
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2674
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0362
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2568
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.4374
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3131
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3663
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4649
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4232
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4476
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5380
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.5242
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5568
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5818
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6426
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4108
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6152
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.7286
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.5835
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6009
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8146
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8730
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.7944
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8417
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.9324
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.9573
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.9700
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.0735
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.9955
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.0289
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1880
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1360
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.1130
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1595
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2873
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1096
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2715
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2427
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -16.3562
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.2743
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3623
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3469
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2973
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3728
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3375
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5485
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.5023
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4207
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4538
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4770
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5346
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6716
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5992
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.5617
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7385
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6432
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6069
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6936
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7545
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7294
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -16.7567
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6941
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -16.8218
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8293
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7772
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8186
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8502
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.9283
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7550
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9502
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9666
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9693
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9442
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.9249
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0512
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0575
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0659
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1248
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0813
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0866
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.1107
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0543
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0265
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0652
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1507
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1396
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1428
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.2105
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2021
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1786
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1550
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1574
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1464
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.1622
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2391
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2274
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2153
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2234
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.2061
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2960
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3095
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3286
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3295
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3198
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.2232
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2913
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3485
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2912
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2786
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3491
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.2385
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3531
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2798
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3516
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2636
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3258
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.3874
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2379
Restoring model weights from the end of the best epoch: 249.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 157ms/step - loss: 12.8916
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.9315
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -2.7367
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -4.8887
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -5.8733
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -6.7694
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -7.2902
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.9705
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.1305
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.7152
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.0645
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.3559
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.2578
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.6273
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -9.7285
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -9.6030
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.1667
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.3261
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.6086
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7456
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7360
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.1097
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.8474
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.1754
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.9751
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.1258
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5857
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.5463
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.7047
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6448
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.6372
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.8422
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.8883
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -11.9727
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.0752
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3218
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.5709
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4752
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.2921
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4908
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6860
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -12.4755
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.9257
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.0703
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7059
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8296
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8763
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.8417
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2034
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.3569
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.2319
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.3110
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.1981
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6220
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4538
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.6711
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.4864
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4168
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.7675
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6470
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.7067
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5904
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9863
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2785
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.0064
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9390
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.8549
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.9450
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.0409
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3465
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4514
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -14.4156
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4040
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4062
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3810
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2510
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5437
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5840
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.5501
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5991
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5326
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3224
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6984
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6841
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.6414
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.8377
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -14.8330
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0126
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.9212
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0145
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3940
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2241
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1810
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5315
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.2220
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0509
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3130
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5249
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5343
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.3153
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5218
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.7706
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5513
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4428
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.7211
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6380
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.7042
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6980
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8038
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8394
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8771
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.9391
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1184
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.7984
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.8524
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.1787
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2945
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2355
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2492
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.9937
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.0570
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3829
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2407
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3282
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2355
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4118
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4266
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3282
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4318
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5358
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.6187
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7592
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8100
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7533
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.7475
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8156
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7952
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0309
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9413
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9134
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9464
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.8110
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0499
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0547
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8064
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9498
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9804
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1003
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.1681
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2077
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3403
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3984
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2270
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2872
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3513
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.2737
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3766
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2776
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3899
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.5384
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.5494
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.6026
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.6553
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.6217
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.6160
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7192
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.6039
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7565
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.6390
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.8310
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7733
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7925
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.8780
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7398
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9175
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9779
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9489
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9865
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9818
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9045
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.9500
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.0276
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1200
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.0338
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.0695
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1149
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1085
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.2332
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1513
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1593
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.2723
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1960
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.2875
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3618
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3906
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.4336
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3643
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.3667
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5020
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3776
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.4802
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.4212
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5232
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5151
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.4931
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6003
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.4785
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5170
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5924
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5988
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6598
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.6542
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6616
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7686
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5974
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5282
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6838
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6592
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.6582
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7027
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7111
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6997
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.6919
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8125
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.7452
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8088
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8715
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7527
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7173
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.7703
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8057
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7586
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8945
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8847
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8570
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.8388
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7211
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8249
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8073
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9507
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8528
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9501
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.8238
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7431
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8563
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8382
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9146
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8696
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -18.8955
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8026
Restoring model weights from the end of the best epoch: 240.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 161ms/step - loss: 20.3432
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3.0805
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -1.8416
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -4.4820
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -6.2042
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -7.1721
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -8.3062
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.9144
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -9.6415
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.4799
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.3005
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.7690
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.3548
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.4871
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -11.8301
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3664
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.0090
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.4480
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.7963
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4747
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.6892
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.4473
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -13.7133
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.2955
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4701
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3572
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.4036
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.5451
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -14.8402
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.4023
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -15.4791
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.3616
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -15.6861
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -15.9921
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.7394
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.0404
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.0110
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.2743
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.2960
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3859
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5193
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4544
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.7642
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.9080
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.5693
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1211
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.3408
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8757
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.1880
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.5184
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.6240
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.4411
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.0874
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.9186
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -17.6261
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.8502
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.7606
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.9997
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.2606
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.3482
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.4785
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.6870
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.3868
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7437
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.8650
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7800
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8945
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.0300
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9272
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.9221
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.0458
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.2264
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.3633
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.4408
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.4893
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.4738
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.6123
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.8023
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.8936
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.8750
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.3477
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.9844
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.8982
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.0078
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.2604
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.5353
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.5597
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.3065
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.4342
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.7165
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.6064
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.9856
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.0258
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.8920
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.8552
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.0045
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.2305
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.1977
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.0141
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.1224
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.2649
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.4891
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -21.6370
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.8089
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.8086
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.8085
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.3513
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.9173
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.1812
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.1030
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.1004
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.0227
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -21.8028
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.2574
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.3178
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.4232
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.2384
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.5649
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5225
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.6140
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.3604
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5682
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5652
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.7930
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.9926
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.0506
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.0272
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.9394
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.1005
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.2092
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.4566
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.2456
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.4421
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.4016
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.3918
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.4822
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.4484
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.5189
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.5441
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -23.7489
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.7626
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.7425
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.8511
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.6926
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.0391
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.9416
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.9661
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.1498
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1000
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1328
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.4456
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.3661
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.2755
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.3357
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.6629
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6130
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.5129
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.5324
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.4840
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.5681
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6918
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.7183
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.8746
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.7651
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.0099
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.1361
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.2158
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.0292
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.1657
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.1760
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.2093
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.1865
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.0578
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.2354
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.3718
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.3299
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.3478
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.5168
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4093
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4868
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.5381
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.3487
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.5535
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.6252
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.7319
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.6896
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7184
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7552
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.8126
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7457
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.8369
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.8708
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.9544
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.9986
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.8727
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.0076
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.9794
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.0908
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.2108
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.2012
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2852
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2258
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.1546
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3477
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.3446
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2767
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.2532
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3072
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3322
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3309
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3884
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.5135
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.3328
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.5501
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.3832
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.5377
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.5888
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.4311
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.4922
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.5587
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.4805
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6862
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6406
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.5950
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6078
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7812
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6373
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7361
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7641
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6881
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6626
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7590
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7215
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7210
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7228
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.8522
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.8436
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6961
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7881
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8224
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7540
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.9165
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7514
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.9126
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.8349
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8964
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7904
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8983
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7603
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8018
Restoring model weights from the end of the best epoch: 242.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.

Computing/loading S=6D (S6D)

INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 198ms/step - loss: 12.0879
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -4.2374
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -8.2293
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -10.5095
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -11.9138
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.6629
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -13.5101
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.3266
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -14.1830
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.0270
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1764
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.5347
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.6537
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -16.0876
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4210
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.3237
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.4001
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.0007
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -16.8687
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2264
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.2430
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.3986
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.5921
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7660
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.7424
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3682
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.3600
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.1840
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5178
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5867
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.7637
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.5671
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8157
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9388
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8462
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.8555
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.2540
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.5835
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -19.4127
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.1168
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.8000
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.7048
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.6059
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.3075
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.3264
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.1257
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.1357
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.8124
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.5551
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.3021
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.4156
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.2157
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.5543
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.0206
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.6395
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.7400
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.7157
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.0139
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.0721
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.8308
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.3125
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.3309
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.8713
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.1655
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.5770
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.4730
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.2881
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.7034
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.4493
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.7526
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.6380
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.6842
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.9835
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.9069
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.8595
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.9026
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.9001
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.7020
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.2038
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.3233
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.1115
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.3116
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.1491
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.6472
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5021
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.3535
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.2920
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.6883
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.8571
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.8347
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.7420
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.8931
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5777
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.7399
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.8423
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.1850
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.9528
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.1610
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.3995
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.1671
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.3185
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.5876
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.4312
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.3252
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.5881
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.6057
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.6549
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.6613
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.8588
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.9036
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.8485
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.7810
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.8857
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.8195
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.7391
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1415
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1508
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.0517
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.0903
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1963
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.3060
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.4349
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.2058
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.4233
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.1813
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.4394
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6861
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.3999
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.5739
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6319
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6133
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.4570
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6297
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.7435
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.9664
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.0349
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.7065
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.9571
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.0892
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.2247
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.9203
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.9819
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.0259
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.1787
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.2162
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.3033
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4639
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4075
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.3482
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4007
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.5236
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.5444
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.5574
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.6498
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7236
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.6119
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.6041
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.6510
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7624
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.6786
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7814
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.8659
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.8301
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.9299
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.1048
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.9168
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.0904
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.0159
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.2268
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3272
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.1703
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -26.0992
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.0467
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.2801
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3189
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.4331
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3857
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.4339
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3545
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.4910
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.3514
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.5368
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.5089
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7728
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6985
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6576
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6648
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6100
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.6165
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7902
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.7715
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.9777
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.9698
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.8819
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.9161
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.9418
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.0884
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.8801
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.0839
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.1199
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.1777
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.0092
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.0207
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.0819
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.1211
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.1769
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.2015
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.1185
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.3231
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.2195
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -27.2024
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3374
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.2936
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3458
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3477
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.2834
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3876
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4251
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3883
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.2893
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.3272
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4023
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4597
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.4974
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4805
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4905
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4077
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4603
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5475
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4681
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4808
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5964
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5095
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5450
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6415
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6488
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5800
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5579
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.5751
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5397
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.4998
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6218
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5760
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5902
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5838
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6044
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6031
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6456
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.6066
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -27.5881
Restoring model weights from the end of the best epoch: 236.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 169ms/step - loss: 16.9638
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -3.1657
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -9.1194
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -12.3305
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.7404
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -15.1690
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -16.5298
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.3369
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -17.5497
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.2758
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -19.4093
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -18.9213
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.6659
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.2310
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.2481
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -20.7729
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -21.2589
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.7029
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.3531
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.9854
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.1592
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -22.5845
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.5712
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.5530
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.8813
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.0873
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.2714
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -23.2987
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.2070
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.7127
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.1034
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.5076
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.1951
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.0800
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.4459
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.5217
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -24.6676
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.3234
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.4861
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.3745
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.5205
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.7304
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -25.7056
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -25.6624
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -25.8213
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -25.7228
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2221
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.3721
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2163
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.1036
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.5868
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7445
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.4859
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7840
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.1036
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8948
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8265
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.0088
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.1274
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.9725
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.5126
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -27.6083
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.5435
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.5888
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.8396
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.7689
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.8168
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.0796
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.3166
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.0380
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.0542
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -28.2396
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.4255
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.4427
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.6458
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.7781
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.2635
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -28.7810
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.0366
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.9359
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.9675
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.2688
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.4351
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.7155
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.5276
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.2943
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.7866
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.6983
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.9415
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.8248
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.0713
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1403
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1126
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.3699
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.3806
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1836
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.4285
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.5732
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -30.4373
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.5985
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.4684
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.6730
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.4255
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.6671
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.7652
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.7110
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.0013
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.1002
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.1825
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -31.1497
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.1696
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.3534
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.4392
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.4282
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.4841
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -31.5502
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.5092
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.8402
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.7604
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.8978
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.1311
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.8913
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9877
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9761
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9606
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.3071
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9620
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -32.2149
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.3464
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.1310
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.6033
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.6490
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.4282
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.7504
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5703
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.6952
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.8647
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.7182
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.0922
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.9748
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.0642
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.1731
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.1866
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.2926
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.3404
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4362
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4718
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4697
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5073
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5774
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.3156
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4481
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5678
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.6814
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.7015
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.0341
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.0480
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.9139
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.0626
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.8877
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.1896
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.9118
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2003
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2669
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2462
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2274
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2394
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.4105
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.3967
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.4062
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.5627
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6598
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.5121
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6466
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.5874
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.7356
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.7261
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8509
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8424
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.9334
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8842
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8212
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.1142
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.0300
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.0164
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.1954
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2836
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.1811
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2881
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2628
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.4224
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.4982
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.3760
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.5110
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.4945
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6063
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6371
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.4803
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6753
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7078
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -35.6874
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6399
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7202
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7984
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7295
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7037
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9050
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7758
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9813
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.8108
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9537
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -36.0177
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.0373
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.0717
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9888
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1444
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1063
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.0599
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1305
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1106
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1087
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2370
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2831
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1196
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2374
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -36.2049
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2221
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2668
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3890
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2705
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3305
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2762
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2627
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3627
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3092
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3475
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3498
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4116
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1897
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3766
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4517
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3167
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3451
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.2402
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3645
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -36.3141
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4696
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3706
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3234
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4803
Restoring model weights from the end of the best epoch: 250.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 160ms/step - loss: 16.6738
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -4.4922
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -10.3737
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.7632
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -15.7642
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.5768
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -18.1430
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.2444
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.9084
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.1621
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.9459
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -21.8480
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.8130
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.0355
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.7197
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.9192
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.5927
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.0417
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -23.9652
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.4306
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.0939
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.0206
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.0751
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.6150
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.0700
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.9780
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.2723
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -26.4133
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7562
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -26.6322
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.8788
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7823
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.5340
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.4582
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.6844
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.7128
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.0610
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -27.8172
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.1342
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.5541
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.2175
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.2505
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.5139
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.6165
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.6603
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.7465
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.7513
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.2291
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.6441
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.1766
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.3734
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.3704
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.8801
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.0357
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.8668
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.8787
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -29.9440
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.2034
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1255
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.5831
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.6554
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.6182
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.8403
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.8640
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.0090
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.2337
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.2811
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.2727
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.1142
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.0200
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.4789
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.6444
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9244
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.6787
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.8149
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.1847
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.9254
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.1278
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.2797
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5931
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.4305
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.2648
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.4606
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5346
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.3440
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5705
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.7490
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.8392
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.8199
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.9052
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.9259
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4362
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4970
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5100
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4556
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.6003
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.3845
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4987
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.3761
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.6456
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.7549
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5805
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.9553
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.9473
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.1934
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.1934
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.2127
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.0990
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.4923
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.5755
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.4918
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6034
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.7597
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6827
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8093
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.7139
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6145
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.6635
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.8277
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.3071
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2117
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.1190
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.5202
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.3503
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.3186
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.5878
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6804
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2291
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.8274
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.8194
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7541
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7618
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9021
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.5194
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9656
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9247
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9704
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.0237
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.5168
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.3479
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4514
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4386
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.5078
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4334
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.5042
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.8720
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.8625
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.6615
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.5714
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.8258
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.9334
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.1625
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.3271
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.0346
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.0266
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.1654
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.3042
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.4327
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.2647
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.4640
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.3950
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.3411
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.6402
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8510
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8580
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.5995
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8162
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8823
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8630
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.0064
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.0240
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8944
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.9914
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.2022
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.1658
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.0622
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.2999
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3775
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3242
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3634
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.2778
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3696
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.4463
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.5491
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.5920
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.7243
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.5429
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.7714
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.9244
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.9399
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.6969
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.8219
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.8546
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.7819
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.9456
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.1742
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.0656
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.0820
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.0510
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.0770
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2189
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2990
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.1324
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2492
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2237
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3173
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2750
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3216
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3557
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3468
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -39.3205
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.4459
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5770
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3519
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5168
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7144
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.6523
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5327
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5488
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5111
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.6173
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.6788
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7462
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7738
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -39.6689
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7828
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8329
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7824
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8177
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.6404
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7193
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7767
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8043
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7452
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.7925
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9106
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8619
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8643
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9893
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8124
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8422
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8927
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8399
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9716
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.8606
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -39.8250
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9631
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9573
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9392
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.9846
Restoring model weights from the end of the best epoch: 239.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.
INFO:bayesflow:Fitting on dataset instance of OfflineDataset.
INFO:bayesflow:Building on a test batch.

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 182ms/step - loss: 29.0889
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -0.4452
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -8.4805
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -13.3541
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -16.2766
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -17.8592
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -19.5600
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -20.9884
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -22.1830
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -22.8730
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -23.9000
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.2431
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -24.7670
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.6708
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -25.8280
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.0156
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -26.7490
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.1692
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.6848
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -27.9915
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -28.6484
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.5543
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.6902
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -29.3783
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1721
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.1663
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.5053
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.7835
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -30.9313
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.3480
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.2522
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -31.2445
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.0039
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.2746
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5979
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -32.5265
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.2592
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.2862
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.4628
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5268
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -33.5342
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.0874
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.1395
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.3297
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.9571
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -34.7354
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.1933
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.6353
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.2466
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.7083
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9071
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.1299
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -35.9191
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.0142
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.4205
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.6449
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.8125
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.1952
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -36.9593
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.0670
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -37.2490
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.6517
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.4439
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8694
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.8671
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.9360
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -37.7902
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3223
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.5637
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.3829
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.0478
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.1763
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -38.6668
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2657
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.3478
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5141
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.2994
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -39.5933
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.2298
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.2004
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.0324
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.2692
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.0300
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.1336
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.5371
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.5830
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.8941
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -40.7527
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.1382
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.1522
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.2783
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -41.2508
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.1282
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.3779
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.4689
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.7994
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.5093
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.7075
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -42.3150
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.4609
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -41.9710
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.4863
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.8688
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.7874
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.3453
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -42.7358
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.0128
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.2951
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.3588
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.4269
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.2641
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.3840
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.2019
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.7535
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.2458
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.3655
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -43.6792
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.1120
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.0077
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.4021
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.5133
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.7549
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.6379
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.6706
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.6626
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.6571
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.7849
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -44.6286
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.2454
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.0845
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.0209
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.3389
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.4475
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.5530
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.6448
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.7244
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.6511
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.6750
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.8676
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.9855
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -45.8962
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.2354
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.1617
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.2636
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.5211
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.4963
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.4268
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.6128
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.5977
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.9290
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.9059
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.2380
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.9871
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.9193
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -46.8977
Epoch 156/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.1844
Epoch 157/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.3257
Epoch 158/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.5346
Epoch 159/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.6533
Epoch 160/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.4994
Epoch 161/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.7086
Epoch 162/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.8077
Epoch 163/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.8541
Epoch 164/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.9368
Epoch 165/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.7855
Epoch 166/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.7713
Epoch 167/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -47.9108
Epoch 168/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.0119
Epoch 169/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.0807
Epoch 170/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.1983
Epoch 171/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.3528
Epoch 172/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.5214
Epoch 173/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.5134
Epoch 174/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.5192
Epoch 175/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.4957
Epoch 176/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.6296
Epoch 177/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.7370
Epoch 178/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.7742
Epoch 179/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.9025
Epoch 180/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.8374
Epoch 181/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.8994
Epoch 182/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.9390
Epoch 183/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.0403
Epoch 184/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -48.9964
Epoch 185/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.0313
Epoch 186/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.0673
Epoch 187/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.2380
Epoch 188/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.1911
Epoch 189/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.3572
Epoch 190/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.4120
Epoch 191/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.5597
Epoch 192/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.4505
Epoch 193/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.5812
Epoch 194/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.6660
Epoch 195/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.7968
Epoch 196/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.5744
Epoch 197/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.7419
Epoch 198/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.7847
Epoch 199/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.9560
Epoch 200/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.8652
Epoch 201/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -49.8659
Epoch 202/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.2767
Epoch 203/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.0770
Epoch 204/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.1892
Epoch 205/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.1297
Epoch 206/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.0565
Epoch 207/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.1979
Epoch 208/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.0321
Epoch 209/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.3118
Epoch 210/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.2411
Epoch 211/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.4318
Epoch 212/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.2866
Epoch 213/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.3219
Epoch 214/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.5096
Epoch 215/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.5734
Epoch 216/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.3103
Epoch 217/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.4253
Epoch 218/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.4460
Epoch 219/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.4947
Epoch 220/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.3703
Epoch 221/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.5408
Epoch 222/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.6817
Epoch 223/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9197
Epoch 224/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.7650
Epoch 225/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.7560
Epoch 226/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.7782
Epoch 227/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8992
Epoch 228/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8911
Epoch 229/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.6956
Epoch 230/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8403
Epoch 231/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -50.6781
Epoch 232/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8787
Epoch 233/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9710
Epoch 234/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.0821
Epoch 235/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8357
Epoch 236/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8568
Epoch 237/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9750
Epoch 238/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.0649
Epoch 239/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8818
Epoch 240/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8656
Epoch 241/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8126
Epoch 242/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9006
Epoch 243/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.1671
Epoch 244/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9663
Epoch 245/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -50.9404
Epoch 246/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.8301
Epoch 247/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.0561
Epoch 248/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.2116
Epoch 249/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -50.9103
Epoch 250/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -51.0902
Restoring model weights from the end of the best epoch: 248.

WARNING:bayesflow:No conditions to infer sample_shape from. Assuming no structural dimensions.

## Cached Files

In [5]:
cache_rows = []
for label, config in summary_configs.items():
    for name, path in all_observed_paths(config.summary_label, metric=metric).items():
        cache_rows.append(
            {
                "summary": label,
                "file_type": name,
                "path": str(path),
                "exists": path.exists(),
            }
        )

cache_files = pd.DataFrame(cache_rows)
cache_files

,summary,file_type,path,exists
0,S=D,results,/Users/yimingzang/Documents/Project/benchmark2...,True
1,S=D,diagnostic,/Users/yimingzang/Documents/Project/benchmark2...,True
2,S=D,posterior,/Users/yimingzang/Documents/Project/benchmark2...,True
3,S=D,posterior_plot,/Users/yimingzang/Documents/Project/benchmark2...,True
4,S=2D,results,/Users/yimingzang/Documents/Project/benchmark2...,True
5,S=2D,diagnostic,/Users/yimingzang/Documents/Project/benchmark2...,True
6,S=2D,posterior,/Users/yimingzang/Documents/Project/benchmark2...,True
7,S=2D,posterior_plot,/Users/yimingzang/Documents/Project/benchmark2...,True
8,S=4D,results,/Users/yimingzang/Documents/Project/benchmark2...,True
9,S=4D,diagnostic,/Users/yimingzang/Documents/Project/benchmark2...,True
10,S=4D,posterior,/Users/yimingzang/Documents/Project/benchmark2...,True
11,S=4D,posterior_plot,/Users/yimingzang/Documents/Project/benchmark2...,True
12,S=6D,results,/Users/yimingzang/Documents/Project/benchmark2...,True
13,S=6D,diagnostic,/Users/yimingzang/Documents/Project/benchmark2...,True
14,S=6D,posterior,/Users/yimingzang/Documents/Project/benchmark2...,True
15,S=6D,posterior_plot,/Users/yimingzang/Documents/Project/benchmark2...,True

## Sanity Checks

In [6]:
coverage_rows = []
for label, frames in diagnostics_by_summary.items():
    for name, frame in frames.items():
        coverage_rows.append(
            {
                "summary": label,
                "frame": name,
                "rows": len(frame),
                "datasets": ", ".join(frame["dataset"].drop_duplicates()),
                "n_datasets": frame["dataset"].nunique(),
            }
        )

coverage = pd.DataFrame(coverage_rows)
coverage

,summary,frame,rows,datasets,n_datasets
0,S=D,results,136,"empirical, simulated_from_m0, simulated_from_m...",8
1,S=D,diagnostic,136,"empirical, simulated_from_m0, simulated_from_m...",8
2,S=D,posterior,544,"empirical, simulated_from_m0, simulated_from_m...",8
3,S=D,posterior_plot,544,"empirical, simulated_from_m0, simulated_from_m...",8
4,S=2D,results,136,"empirical, simulated_from_m0, simulated_from_m...",8
5,S=2D,diagnostic,136,"empirical, simulated_from_m0, simulated_from_m...",8
6,S=2D,posterior,544,"empirical, simulated_from_m0, simulated_from_m...",8
7,S=2D,posterior_plot,544,"empirical, simulated_from_m0, simulated_from_m...",8
8,S=4D,results,136,"empirical, simulated_from_m0, simulated_from_m...",8
9,S=4D,diagnostic,136,"empirical, simulated_from_m0, simulated_from_m...",8
10,S=4D,posterior,544,"empirical, simulated_from_m0, simulated_from_m...",8
11,S=4D,posterior_plot,544,"empirical, simulated_from_m0, simulated_from_m...",8
12,S=6D,results,136,"empirical, simulated_from_m0, simulated_from_m...",8
13,S=6D,diagnostic,136,"empirical, simulated_from_m0, simulated_from_m...",8
14,S=6D,posterior,544,"empirical, simulated_from_m0, simulated_from_m...",8
15,S=6D,posterior_plot,544,"empirical, simulated_from_m0, simulated_from_m...",8

In [7]:
posterior_summary = []
for label, frames in diagnostics_by_summary.items():
    frame = frames["posterior"]
    posterior_summary.append(
        frame.groupby(["dataset", "model"], sort=False)
        .agg(
            mean_mmd=("posterior_mmd", "mean"),
            median_mmd=("posterior_mmd", "median"),
            mean_posterior_mean_rmse=("posterior_mean_rmse", "mean"),
        )
        .assign(summary_dimension=label)
        .reset_index()
    )

posterior_summary = pd.concat(posterior_summary, ignore_index=True)
posterior_summary

,dataset,model,mean_mmd,median_mmd,mean_posterior_mean_rmse,summary_dimension
0,empirical,m0,0.219341,0.154009,0.238050,S=D
1,empirical,m1,0.227051,0.175034,0.194805,S=D
2,empirical,m2,0.211853,0.221962,0.220987,S=D
3,empirical,m3,0.306619,0.212100,0.259090,S=D
4,simulated_from_m0,m0,0.010768,0.008996,0.040133,S=D
...,...,...,...,...,...,...
123,m3_slow_30,m3,0.065447,0.056301,0.102677,S=6D
124,m3_fast_slow_30,m0,0.281155,0.179708,0.416993,S=6D
125,m3_fast_slow_30,m1,0.442371,0.418471,0.477028,S=6D
126,m3_fast_slow_30,m2,0.095229,0.064474,0.140913,S=6D
127,m3_fast_slow_30,m3,0.129545,0.101563,0.140690,S=6D

## Density Flow Held-Out Validation\n
\n
For each summary dimension and assumed model, compare held-out simulator summaries against samples generated from the learned density flow. C2ST accuracy close to 0.5 indicates that the classifier cannot reliably distinguish the two samples; MMD should also be small relative to other fits.\n

In [8]:
validation_rows = []
for label, config in summary_configs.items():
    references = load_references(reference_path(config.summary_label, metric=metric))
    for model in MODELS:
        ref = references[model]
        validation_rows.append(
            {
                "summary_dimension": label,
                "model": model,
                "c2st_accuracy": ref.get("density_validation_c2st_accuracy"),
                "mmd": ref.get("density_validation_mmd"),
                "mmd2": ref.get("density_validation_mmd2"),
                "n_simulator": ref.get("density_validation_n_simulator"),
                "n_flow": ref.get("density_validation_n_flow"),
                "typicality_low": ref.get("typicality_low"),
                "typicality_high": ref.get("typicality_high"),
            }
        )

density_flow_validation = pd.DataFrame(validation_rows)
density_flow_validation

,summary_dimension,model,c2st_accuracy,mmd,mmd2,n_simulator,n_flow,typicality_low,typicality_high
0,S=D,m0,0.5135,0.049187,0.002419,2000,2000,-3.899140,2.380388
1,S=D,m1,0.5260,0.047284,0.002236,2000,2000,-4.559561,2.515721
2,S=D,m2,0.5040,0.054664,0.002988,2000,2000,-4.696848,2.605484
3,S=D,m3,0.5130,0.034037,0.001159,2000,2000,-9.360566,4.760859
4,S=2D,m0,0.5060,0.038967,0.001518,2000,2000,-6.096990,3.978201
5,S=2D,m1,0.5075,0.043318,0.001876,2000,2000,-8.099177,5.115617
6,S=2D,m2,0.5030,0.033492,0.001122,2000,2000,-7.577586,4.547107
7,S=2D,m3,0.5315,0.050568,0.002557,2000,2000,-10.982581,7.347402
8,S=4D,m0,0.5145,0.029674,0.000881,2000,2000,-10.362528,6.971862
9,S=4D,m1,0.4935,0.038282,0.001465,2000,2000,-14.912279,10.095640
10,S=4D,m2,0.5215,0.042847,0.001836,2000,2000,-13.712436,9.257514
11,S=4D,m3,0.5080,0.032587,0.001062,2000,2000,-22.514249,14.872143
12,S=6D,m0,0.5230,0.040662,0.001653,2000,2000,-16.618686,11.397464
13,S=6D,m1,0.5205,0.043182,0.001865,2000,2000,-25.484884,16.887687
14,S=6D,m2,0.5125,0.033274,0.001107,2000,2000,-22.358819,14.892164
15,S=6D,m3,0.4990,0.040102,0.001608,2000,2000,-38.880425,26.040330